services:
  burger_orderer_test:
    build:
      context: .
      dockerfile: ./Containers/burger_orderer/Dockerfile
      args:
        SOURCE_DIR: ./burger_orderer
    command: ["pytest", "-vv", "--tb=long"]
    volumes:
      - ./Containers/burger_orderer/src:/app
    container_name: burger_orderer_test_container
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/
      - KITCHEN_URL=http://kitchen_view:8090/
      - FLASK_ENV=testing
      - PYTHONPATH=.
    depends_on:
      - mongodb
      - kitchen_view
    networks:
      - database-network
      - client-kitchen-network
      
  kitchen_view_test:
    build:
      context: .
      dockerfile: ./Containers/kitchen_view/Dockerfile
      args:
        SOURCE_DIR: ./kitchen_view
    command: ["pytest", "-vv", "--tb=long"]
    container_name: kitchen_view_test_container
    volumes:
      - ./Containers/kitchen_view/src:/app
    environment:
      - FLASK_ENV=testing
      - PYTHONPATH=.
    networks:
      - client-kitchen-network

  mongodb:
    image: mongo:8.0.0
    volumes:
      - dbdata:/data/db
    networks:
      - database-network

volumes:
  dbdata:

networks:
  database-network:
    driver: bridge
  client-kitchen-network:
    driver: bridge