services:
  burger_orderer:
    build:
      context: .
      dockerfile: ./Containers/burger_orderer/Dockerfile
    container_name: burger_orderer_container
    ports: 
      - "8080:8080"
    volumes:
      - ./Containers/burger_orderer/src:/app
    depends_on:
      - kitchen_view
      - mongodb
    networks:
      - database-network
      - client-kitchen-network
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/
      - KITCHEN_URL=http://kitchen_view:8090/
    stop_grace_period: 1s

  kitchen_view:
    build:
      context: .
      dockerfile: ./Containers/kitchen_view/Dockerfile
    container_name: kitchen_view_container
    ports:
      - "8090:8090"
    volumes:
      - ./Containers/kitchen_view/src:/app
    networks:
      - client-kitchen-network
    stop_grace_period: 1s

  mongodb:
    image: mongo:8.0.0
    volumes:
      - dbdata:/data/db
    networks:
      - database-network

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    ports:
      - "8081:8081"
    networks:
      - database-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

volumes:
  dbdata:

networks:
  database-network:
    driver: bridge
  client-kitchen-network:
    driver: bridge